apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: create-todo-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: create-todo-cronjob
            image: jacker92/create-todo-cronjob
          restartPolicy: OnFailure