apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: exercises
spec:
  encryptedData:
    password: AgAqSyriOZH4j5CPfbYQdgGOc2fJ/ymHgGCX5Evwt9QMRf/EP9vl2XkX/supUR1htgoVGjJBYc7faKLEMvl83T91AM6u3z48NiUNlXFCJ21ZsjbDagKlMVgRX2t3O3bEy9eDwcNbXA9pVbddKfZPPJEiHyzuX0WZFBbKFsH3mpXEV0cqgzjT1qRcj9mSLNyeP92C7ZBPV2F/1fq9P5lYXPwdrWL7Q5w03yPchDwJvXHDLhksoJ/v7Et6T7qW29eJ/+CSa4sReGUKee90a6KUz5s5Oa/24LQv4PDbN3+0+a1neJuDyjjlm3oWrZxofbTntPhI75a4HJFf2TwAhQ6krji94iekQoe9LO0HOarEwkRgbbmB+DqZ0YUBz5qA9NoM4dNd0R2SSsS7jc6h3hG9Og8ByD7PV3GkXAQJ8jyeWJYEQ3Xio+O+j66igZlh3ET7fK7Ishg9yd3KfJOwsSe+oGiOAIqyaohN8OhMd/XPrq1KqgUUPYOgCm8eC7K7q+VYX/4s+PWzP7+txmumyQC8eDDMo7HWrjMd8DGXOyPaNwzyFrl7e+r5dnTP1OfFSY28S/axs0CrtcPEdrRD4OeLjYO2wOIqy8nN2giQn1dzBAPRrOf9hsisVCUCz/TlEG7RJ1UKjl7h0mFnzKXHWEqtlPwA6q8YJDRv4+1FfUbceRl/qxYaVJnmwbua0GT/xs/4rIYrDjr1EfmN7Q==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: exercises

