apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: exercises
spec:
  encryptedData:
    password: AgA1d3k4BgpRbd6LLHjtlfKSKECBHjWWlqmE+XyJEFk3YEOC4FZ/HIdbNo67mpEFPmuzFEI1+wlT6hRTGgJUXgKJ703vC8xNMFnVMI1iGGhQjVZMFbqRwqX0TOgBH9W5fcaujWVVbR6hPCd98RFirnk23EHOBVvLmQUXbw9y5+8tpHn7AN1tpLPCCTWxZIDu6B9QwWDO7AHuju70KCrO8D63B//lg+TmgA9h7OKB3S8wnwg3x4gBKpRpsccQ6udlzNY3dKa7OcF4yvr6GsKjegvspB8mpOucUpGXYhL1eW59YR0r0GCYepj5LL3m74VqCLpdHJGN76EQ5UYRYAH4iPebJ6YftfFR8JWlbEDdfDd6pg/Ks+4ufZwH6IE2KF+A/deVsk6njL4EWXKxgsYOck7c3DlaVdMyHNrKi3eoWRkD/v12EOGbELURC8okF6UaV3HB4LLZp9yccafV9kvCidHm95QKv8ishImgNFftuATkL1QoeIevamX8c9vGxx353Ww9bVbwI5DTnQ0Q1RfBcuHlP0pZYbcb1OF49VuOPhcaeJ/kRVOqFsTbtQZXAJ663x/XzUMilCS0wfcs7pEFUctjmLq6WWqqWVUIPFweO1o4oBWaSmP5FmsrBpb7fAqfb++UUaVS3+TFVlUd+SVSI/cbIFqKsZRSUMKBT1qhDU0uiZ88w/Ytkt6I81wcqCACoz6BWjZEg2OQ+g==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: exercises

