apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: exercises
spec:
  encryptedData:
    password: AgB49pxDwxxy2zD62+ECW9va5fTTDphnAQ96Vsb6NC+6GyJzjzB0Ng474h2sxlPWEtUG5Guje9/UZp4O7/CK1R7cAfTbnwSBUBlcPq/0zS15XwUwqos2j3248oESGkFgpScwJCM9DFG6kAD6FksjruiUA8oOhe6jNIpr/AktUWNcmvhEKTKCYW+DznWka7FAol4fLvW8QqHJLfuxPRypLXolsmz8dcxOQq3EV8FsLl3HjIRoLgRS7rHLSDSq5qIffl2UJ1yxQEc898tkbfA5MGuem5oSJfULXtHN3K6tIB9K4fzGts1aaSaxjkKxC4yOc81uKmvgG1fvQuziKK9JCa5cZJ7N38frOyLwPoel/iHbPi1UAd4Z7zs6bnfsa0PFLrXZ6REeJ939r0TecwZHrAzAk7CjAaFNU0c/kWCbX77/bLo8jT/z1eIQqZLya3FrmJe/Kl3ig0uczYhkb7ud1w6Xrhu+ScbIPqe4nB7K8N/EnVK5NX0ulOjeLw1To/YwWtmHa/mj7L/Au/GuEOl1BOPEcEDEkCmJgKjPmjusYUeyEMK7ES8rYzOjblPrT5MI661CpZZCMv3XtHZ/7UFWvBsLuPd9ZwrgKzlwDXWMq68d9dTnxhcvwxVscIgojn6CX6GV/8V0AzFpCTP29mb5TdHzyJjAgXex8yeWzaRO7lDCh3sGSEnKc1EhzWrDs5u+z/jnPKs5PnBT4g==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: exercises

