apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: exercises
spec:
  encryptedData:
    password: AgAKLLSJhVRZ/BoFpyg5EzwjA0KyylFjfUwjhQl/6hes7YU55QDiwS9oFrga2WZWGVyjzEXBODt96fRH/LaNQQGNR19i81OfDfsBgg/MPXyzAwmNEKNkd7buC5rwHMni8cYGuY98MlLNDGnELG1TlIVceTqiHj9KPUnsSG7M1+3Rbo8wa2o0wDCPnoSVLSF7Cj2VGOI4bS2VAc5zLF750V+D/dCquIytJqKPUUxerW6+jopqLkDnzlfltlomElr34aPHnUFUaGhce1Mald57tKs3brWmgcmzB1AOIg7/Da9h9iAHvpJxf9Q6EFFBk91YoJzU/S5TylEhyFGojZJYDery46InyAHRCiGaFZWUCHsxfP4S9xYzl4DB3nd/oXxwi/gmZMR4amXGHCw3Sl7AnqmbLFDXnSPZCeaNsQ/oKooyyC8xRE2tnE/o0XG/gfDSEhiMTPUegmBhA8kFOuTij8I7ATSDZqs+ijRy/qAkex0kKP8cqEg8CObYmf1VNKKWM6tJ85X7MrFMMvU4SKj1lUfcXei1uX4VHmq9XrNgl1agik/S/hSKGdHw0Yw3AfUfOxMe/W/1C+zULHtDFWMdc5vW3m84WxyX41YMFnlDIY8BdUEzqmJC7a1/shvQ8EobT4jUevCHjcU5rm8K1zzmrVQKRhYGsQiRXkA1FTiNwRTfRFi5JiZOiRv85P/k5laxaSJGGlrP1GCtgA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: exercises

