apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpukiller-dep
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpukiller
  template:
    metadata:
      labels:
        app: cpukiller
    spec:
      containers:
        - name: cpukiller
          image: jacker92/cpukiller:latest