apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-frontend
          image: jacker92/todo-frontend:latest
          resources:
            limits:
              cpu: "25m"
              memory: "100Mi"
        - name: todo-backend
          image: jacker92/todo-backend:latest
          resources:
            limits:
              cpu: "25m"
              memory: "100Mi"
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password