apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-frontend
          image: jacker92/todo-frontend:latest
          resources:
            limits:
              cpu: "100m"
              memory: "500Mi"
        - name: todo-backend
          image: jacker92/todo-backend:latest
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /
               port: 3001
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
               path: /
               port: 3001
          resources:
            limits:
              cpu: "100m"
              memory: "500Mi"
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: NATS_URL
            value: nats://my-nats:4222
