apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - service.yaml
  - deployment.yaml
  - postgres-deployment.yaml
  - postgres-svc.yaml

images:
- name: BACKEND_IMAGE
  newName: jacker92/todo-backend
- name: FRONTEND_IMAGE
  newName: jacker92/todo-frontend
- name: BROADCASTER_IMAGE
  newName: jacker92/broadcaster

