apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
  namespace: master
spec:
  encryptedData:
    password: AgAaBo2Nswk9Pu42tRELK8u8g1bzEkyltR8I4OzVocXySVxYmsaXs+ymvvX0H7nUxhu1XNVU3BuwUtkhyoF+Nu4ST+Jft17f0lKNGNPPvtVpwrHLPaF/gHTVQlxdBWPaYzzCq90xPKdxvQBTI+e7IxoRVHAnBo+LCavsmJEBbYYLcXzdx+ia3Q2LoEfEg5XwHRo4oXbDBkxB08eU2Bv1C8A9mmad16ZfqrglNwhxR2/aJ5iTTxl0QoA3EjCGhxknnKeYynphI0LNluD+sJGUYhwRGUr62j0JoloNUguuLJ5R97bDjYBW5TjocRsYKI+sje3BMGxQicgeBxjL9V058e1X+j85d5lT/kPO6NY/n8nW2AuEJ07TTK/NyjbWj/O+Nxo+Qm4+dYAP755KcWNXzFPaPkP0ZxgDjQFvhapUlyFVCb1Fuvg+O8rd24tmwsFd35e12pLH2rSVjw5Jpm2rBmcZIaPZ36exLru6ggsce1i8KkrbCr8lgtMpPGB7WXjWgvxMCwmJUogrvnM92Qlme6JNya8Do9UMjrGEbIAmyIvZH4L7RBU83PGq8K4mlIvR5c+ySjqGhaY5iL1wgYwmyRRnjhE9ztR0HeaQ036q1o3ZMdNE08cu36UK69rQyBAr572Qep6EU2Qm1BAzYvDKt+xZTWGm6VXBZPAoMKqooLf8Zcz8JIEMkqecaneKTUKupBWCFQLJmgSTNg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres
      namespace: master