apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
spec:
  encryptedData:
    password: AgA41QKn5aoFBpM/Ef1BhmpsmOqQRnEFdutF75T6QWXWBUQdBWJvxrFd2eCvtyeEZSQC8COQZwrVeqZKvMhBCD2sLb2wwQ0C1JXP5WdkicFyTjDUva1WKCygUn03twEjao6xkEauqFeumWNpezRWswml9YLfOX6vX+Hbvlv0fegtY1+0pJGXeziQJMmZtcKIp1J5tkUImXVcggq3z7Qez0PakMhXkgNkKBnkZgoevf7a2ojbZuTNvTrmdDTqFNwrWQAM1KdBFS9m6HiFVSQX7+f09TQYPuClgtXwe8XfzZLnqEuvpqwKKawErdZwjIwCDSv5gR9GUZtmEbCK5Ia8g/fl0SCiJGNR8UWTj5CaO1YTzAa9Mi/V9QQlS0GwcL7LGHLhtP+mV7NY/U2xzeX7ouEMWFE0jT9Cq3RzswqXORGFg5s+FD7/2NA/m+PdK15AWD2OcUoyuncnOG1y/SkLAoUtyLX8pUfHhVpDnw2lvgSqGLo6iL5XwgNdibKAWIui4x36PtJR98r80DQAtnc1rUF13YzqHrDYWTwlzqagNSEjrxCR1UQL2EjRsWCSUPULN/VdLtUDdSe7KgtrhZv8TYHuF7Q4CaexzSisGHFNLhBmPiBuLjTcoKtZ9OBi8nAdGN0wi07S4yIWGtC9uOtHBb5uCDKwidD/TBM0DrH10dNwqWAA1iYD01LavZy6olJx24sE9cjsWQRKfQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres

