apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: todo
spec:
  encryptedData:
    password: AgADgnbS7bREMn+JF2Nre/71Uc4CkTIy8mRSeVa0Lo2MkK+ESc0YbQKmM4zz52ob5t/Z8GeCrH0+ZwMjJ2PJs0dJ9od6DAFR7tP/Vbq76ynlkjIgUiCHW2re1LaQvDrrZb8oFwMLMgsEkrIhxd/Rvox9eJUXsJv5Qfvofj1+arzBFcpTibh8+HdQs6PQD3NWXzobleK4duSIvH5nXjZhrZOpCg62EfkQL3/4cU37gjm7Kbf7jL2AL8QwDt4fbRlUsVO98Tz8fW2cFkYXJOYTQNikHDTS3tVbB5SX4GpQxRfqpnIgvNXroIWEd/yDSRag5rNh01CaWutOdtWB48mDBhUwkHbqYSPpMrBitMuT8f8U8ebY9E2L7VVqOYVVPfXVHUtscb/mXrtIRkNJioTH1XRND2pgjsmnp72QMxjIMiy9YEGRzXLuAZd3Ij22ClLKqJv5dJgqyttBAXA4Sg3hVwcV+NmzD7xUtLl142R+IKC55hCIqjYX0ihUaSwbf7IZvr1fMuNFSLcgsN9P+5SRD7cL9Y6Zw3Ec64yZopo3nXmprXByVBl0+/hIjdsbEiApoQO92+bzgWJ0SFfPKOYpmeYJTvq5swTPLmgZkkwGOiZspy6gmc0o1VA0YQIhHxvwuKY3tuNyulLmF3hgfMv1I5/ZHFI8AK9mkUx3rDAKOo/y/6poI7QO34UF+L0FyArthSsUkXVq/3cjkA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: todo

