apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: exercises
spec:
  encryptedData:
    password: AgBJ6sJdIYG25iihXS/P+Q/40K8ImzZzrglkg7fi75IytS+7VqW4KpCVhcGawf9AmBpX2PVEv6eykquxzXalEB6cIhEpLAVWL/y7qocekey4Oo3b5tr6HCFl8bTZnJk4lugr2V/u44ASd+L8YkVbdYHO/kxszVjuIhcem8LbtfzdipuBZY08xuh9N1ANuXzOKL0DprrLO6gJqXSt1a1Bf19BvRcfyOWVtrkojJC3TY6sKV0FZDe4siMW2qznizOT6t7YQqFGha/uhUSKURHYcs0tO4YutBemYZov7Q6rqskyev8MeY3MRQaWT5dXvVh14wbqCWsXL0m9BAgDJGb439FbT8GqMO2N1MJELeoYbf7iIw0RtSEjUkbZpeZ0mhc7eGFUgHQtUwOY7PtkzfTuUhOrp/ZeG8aDo375LZKRErxf+Qq6YB/hn+STCzsRku/iNBapjQxlTW4ZAv/NiCq9LaPlJ8cgNXfIwbxtrumkjUPgsD51Dv1f1KAjpNnpn4y97gYmBMa1rRJS/DkvWVIC5+jr+l7k8jbzhQ24VWowcUKZcKRdsmLQs7n6qaHxlCUasu6hpCFVo0rYgKKaXeGeELxPk6O2GabGppCy7TR5ebR8pzdio6K3tWYHBUdr23ln272d5enTfg9r1Vj3Cg2TDlzK1rJT3LAuqSKt/dlDGeGg0RvOPEYzTRkQVieE3DWt/OdfL5mHjf0lQw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: exercises

