apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
spec:
  encryptedData:
    password: AgCsoIZ5JunnMUwhRmCOcQj8I8V+IH49/oINyDi/1534a7y4WZ5iL0djbjSdVbDNo3ckQHFJ74yWvqhu3VlHFd70HnNgBW4IvPOOXwVOSLU26vaP7o7YEne6jMni6ksU91LGtWBWJqAHsIbwzJEBpT4qVpnCJTljmYIc86uU4OVG2980UJqLuz4ij3gAZApqe+wBomcZ0klnOtOeDg8hx98QBKH2llutZiuX6g7bc7S4J6+w+gq6nSuDnrayEi03v5PFFPfiKtgHl0TgyGmwFvxRKuGZepsCcy7SVxVWd3g3nrOjAClQmVap+sYwnfTGHk9ZeTnn2pY2aCf2QkGZoghtEHaj/MNeZQ4W5upPyLFANNTbS+xz76glew/SdiIyHb8Sfxzrp81UTBOpne2iQ6BJAdDGHAr1oIuuB/WzkC05gWPkk9p/9R/b8tpzILmUUk39DD3+/5dYPSahlXPGrv8gBeW7siL4Z6XrTg3pyipPeiNZKTBFA8ZsXxP9p+rAnEmlVuH0oDJP1ELbQZcYPPA/qr1sJkX7maHDVaUs86H3HhqJl+JwUY8Mop6Qk2SVc1rBY5dzxKxC8g54I6blpsBUejD/46BIITKhImuB+cEqrAiqQuBe6+JMnN5zWWz0SfuqZr2Sm+j2sBwgTH9PmIXD5zY4cr7ks7wPS081OEKFKHqevqItfZPkMvhTDL8XnFZ7KDj67RCJQg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres

