apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: todo
spec:
  encryptedData:
    password: AgAmunI/k9JuZAB25Ggq88Xqe15F0ZXpvtdxqVE4a+Lea9lSskwnwbHMFzJ0sJ2aGyvr8+/djAXECG11RkgE9SZfF7/sjZtD9YYwPg9FeUTIkrm+b30Bq09DdQc+0HmGf/93ToWDClAP16onF34trE0fy84nPnrd6g8s3c9lF0Y99HDLhPohvDC+HMRDj66ITaFecA2tAt9E2WL9W0nXehxsC2aMguG7ddI3wSH8QDppWJlnFAHvYjQGjQuWwWWTyoeOGYiGcf2iBTI61acAOS4kTgZMB6CFOVjaehjImPXYPCvXvNexpOfjxfy6FzLmLh7ZGLwxc930AR9Z4bwXLBYCC70W6wokdNjNigCcTHgqz2I1OdlPcqMcVnPX7eJNLf1M7riqTUcPJQTwV9br9OUvxkzs7gI0VMB2DLfCGVm+6jHnxxzk/Fgw+ICyxKQq8v1qx7Cmlfrf5n+NXa/tr4kcpo6mEyYRH1+eXzoPrre0kG5vBbzcZ4dT6Se8JReUwl7rxhivukuv9wdOxPdKG8jT20Cjt/C7jaufn7+mvTw33g26CUWtkZt1C+WwDNoYFe6aPjlHbowyQ9rNI09ZQ2jzqUyQD7b7FoTUYjhRSyKqa85F3vFlKohiJUQz3RqSLRULFPJ+0j4Hbvq2YmOj+5mfe0+X22mc6nIuXld2cKsM0eW6m19//1pv8n1V5+nvdaNKRk1veTPEAg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: todo

