apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: todo
spec:
  encryptedData:
    password: AgBrpRiLPM0edvqBzBRjCrZSeAWuEQkg8ZUm73A7JUSDUsS4ZiQHcHG/rvzsG1rSf7Wsp3X7UgH762bKWZfWbR48ToouuNylBQm7kB60y+HPtM8xI0bkz273bmhmpahSYIYLIUVcHNKSDbzs6RDMZ5KV4N4dt7ERzOZMYnXo3NjMRR0EDOAc7xeRw9rsBvccYOuVm6SECnehAnPdy8o3R6qJPsEsFRmwS6dkoR3TboE1sn6DvX8c2Xo4M+JboonHORBoowLWWv6LGClhyjje1JOQNYHw2yAyZAhw0mS9GDNfUwLn5UBX7jDelUWE4WuoLoJ8OR0TD2IiJshw/ePyDx64+d8GZsH65bxQoIcuiF6Jo7AMgFPc96NWZhkiR90UUNsNYK38xwkFck4bdphTlDrcX9KwASyMahNFkD1CTJubrC0v2Or3nynNr+7lc2eWcYb8POJU2ErRwl7monRuXtyUUqC5MWJWwgZTq/2+xMl2HqP6vKno7fXYcAnswMWmgJGYcL1RUihTXLv52UlJcOGhqqGrQE7Y7Tud7YqDS60HIKLDyQsFTti/6jW+9+/cesCgiggpSkq7z9LnDMqMEFxpuTXvYIvAC04u4+jJ4RjDnBrFeC6RLcgBrdAzQBlpeNHSCvOyNiHHw9AMdOMzpD8kdbjpmOZA7lKOyG8nGel364Bt3G3novOI3665vx/QDavS2+JeswBYnw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: todo

