apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 2345
      name: todo-frontend
      protocol: TCP
      targetPort: 80
    - port: 2346
      name: todo-backend
      protocol: TCP
      targetPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 2347
      protocol: TCP
      targetPort: 5432