apiVersion: apps/v1
kind: Deployment
metadata:
  name: timestamp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp
  template:
    metadata:
      labels:
        app: timestamp
    spec:
      volumes: # Define volume
        - name: shared-image
          emptyDir: {}
      containers:
        - name: timestamp-writer
          image: jacker92/timestamp-writer:latest
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files
        - name: timestamp-reader
          image: jacker92/timestamp-reader:latest
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files