apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: timestamp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp
  template:
    metadata:
      labels:
        app: timestamp
    spec:
      containers:
        - name: timestamp-writer
          image: jacker92/timestamp-writer:latest
          resources:
            limits:
              cpu: "25m"
              memory: "200Mi"
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: dotenv-config
                key: MESSAGE
        - name: timestamp-reader
          image: jacker92/timestamp-reader:latest
          resources:
            limits:
              cpu: "25m"
              memory: "200Mi"