name: Cleanup on branch delete

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  setup-build-publish-deploy:
    name: Setup, Delete
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - run: |-
        gcloud --quiet auth configure-docker
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Delete
      run: |-
        kubectl delete namespace project-${{ github.event.ref }} || true