name: Release todo-app

on:
  push:
    branches:
      - master
    paths:
      - 'todo-app/backend/**'
      - 'todo-app/frontend/**'
      - 'todo-app/broadcaster/**'
      - '.github/workflows/todo-app.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish backend to Registry
      uses: docker/build-push-action@v1
      with:
        repository: jacker92/todo-backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: todo-app/backend

    - name: Publish frontend to Registry
      uses: docker/build-push-action@v1
      with:
        repository: jacker92/todo-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: todo-app/frontend

    - name: Publish broadcaster to Registry
      uses: docker/build-push-action@v1
      with:
        repository: jacker92/broadcaster
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: todo-app/broadcaster
      

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      working-directory: todo-app/manifests
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      working-directory: todo-app/manifests
      run: |-
        ./kustomize edit set image BACKEND_IMAGE=jacker92/todo-backend:${{ github.sha }}
        ./kustomize edit set image FRONTEND_IMAGE=jacker92/todo-frontend:${{ github.sha }}
        ./kustomize edit set image BROADCASTER_IMAGE=jacker92/broadcaster:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: 'todo-app/manifests/kustomization.yaml'
        message: New version release for todo-app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
